### ISSUE TITLE
failing to build pages

### ISSUE THREAD

**Issue by KazuCocoa** [appium/appium.io#302]
https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=15025&view=logs&j=b9a26d17-edd7-534e-d332-dd86d02f1216&t=356869ca-715b-520e-c4c5-1c813195bf19

```
2021-05-02T08:14:11.9633735Z info APPIUM.IO Cloning Appium from GitHub
2021-05-02T08:14:11.9898373Z (node:37) [DEP0128] DeprecationWarning: Invalid 'main' field in '/root/node_modules/mjpeg-server/package.json' of './lib/mpegserver'. Please either fix that or report it to the module author
2021-05-02T08:14:11.9899885Z (Use `node --trace-deprecation ...` to show where the warning was created)
2021-05-02T08:14:17.8417134Z dbug APPIUM.IO Building HTML docs from Markdown /root/appium/docs
2021-05-02T08:14:17.8432445Z dbug APPIUM.IO Setting base url to /docs/en
2021-05-02T08:14:17.8646135Z dbug APPIUM.IO Executing 'mkdocs' with args ["build","--site-dir","/root/docs/en"] at directory '/root/appium/docs'
2021-05-02T08:14:18.4614897Z ERR! APPIUM.IO Could not build
2021-05-02T08:14:18.4617227Z ERR! APPIUM.IO Command 'mkdocs build --site-dir /root/docs/en' exited with code 1
2021-05-02T08:14:18.4623491Z ERR! APPIUM.IO Reason:
2021-05-02T08:14:18.4630844Z ERR! APPIUM.IO Traceback (most recent call last):
2021-05-02T08:14:18.4637100Z ERR! APPIUM.IO   File "/usr/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 366, in walk_docs_dir
2021-05-02T08:14:18.4639807Z ERR! APPIUM.IO     raise StopIteration
2021-05-02T08:14:18.4661984Z ERR! APPIUM.IO StopIteration
2021-05-02T08:14:18.4662656Z ERR! APPIUM.IO 
2021-05-02T08:14:18.4663361Z ERR! APPIUM.IO The above exception was the direct cause of the following exception:
2021-05-02T08:14:18.4664040Z ERR! APPIUM.IO 
2021-05-02T08:14:18.4664601Z ERR! APPIUM.IO Traceback (most recent call last):
2021-05-02T08:14:18.4665237Z ERR! APPIUM.IO   File "/usr/bin/mkdocs", line 8, in <module>
2021-05-02T08:14:18.4665777Z ERR! APPIUM.IO     sys.exit(cli())
2021-05-02T08:14:18.4667186Z ERR! APPIUM.IO   File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
2021-05-02T08:14:18.4667980Z ERR! APPIUM.IO     return self.main(*args, **kwargs)
2021-05-02T08:14:18.4668913Z ERR! APPIUM.IO   File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
2021-05-02T08:14:18.4670116Z ERR! APPIUM.IO     rv = self.invoke(ctx)
2021-05-02T08:14:18.4671062Z ERR! APPIUM.IO   File "/usr/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
2021-05-02T08:14:18.4671881Z ERR! APPIUM.IO     return _process_result(sub_ctx.command.invoke(sub_ctx))
2021-05-02T08:14:18.4672871Z ERR! APPIUM.IO   File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
2021-05-02T08:14:18.4673654Z ERR! APPIUM.IO     return ctx.invoke(self.callback, **ctx.params)
2021-05-02T08:14:18.4674663Z ERR! APPIUM.IO   File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
2021-05-02T08:14:18.4675374Z ERR! APPIUM.IO     return callback(*args, **kwargs)
2021-05-02T08:14:18.4676557Z ERR! APPIUM.IO   File "/usr/lib/python3.8/site-packages/mkdocs/__main__.py", line 150, in build_command
2021-05-02T08:14:18.4677332Z ERR! APPIUM.IO     build.build(config.load_config(
2021-05-02T08:14:18.4678276Z ERR! APPIUM.IO   File "/usr/lib/python3.8/site-packages/mkdocs/config/base.py", line 181, in load_config
2021-05-02T08:14:18.4679082Z ERR! APPIUM.IO     errors, warnings = cfg.validate()
2021-05-02T08:14:18.4680046Z ERR! APPIUM.IO   File "/usr/lib/python3.8/site-packages/mkdocs/config/base.py", line 105, in validate
2021-05-02T08:14:18.4680777Z ERR! APPIUM.IO     post_failed, post_warnings = self._post_validate()
2021-05-02T08:14:18.4681964Z ERR! APPIUM.IO   File "/usr/lib/python3.8/site-packages/mkdocs/config/base.py", line 85, in _post_validate
2021-05-02T08:14:18.4682799Z ERR! APPIUM.IO     config_option.post_validation(self, key_name=key)
2021-05-02T08:14:18.4683830Z ERR! APPIUM.IO   File "/usr/lib/python3.8/site-packages/mkdocs/config/config_options.py", line 391, in post_validation
2021-05-02T08:14:18.4685081Z ERR! APPIUM.IO     for filename in self.walk_docs_dir(config['docs_dir']):
2021-05-02T08:14:18.4685856Z ERR! APPIUM.IO RuntimeError: generator raised StopIteration
2021-05-02T08:14:18.4686386Z ERR! APPIUM.IO 
2021-05-02T08:14:18.4687232Z ERR! APPIUM.IO Error: Command 'mkdocs build --site-dir /root/docs/en' exited with code 1
2021-05-02T08:14:18.4688103Z ERR! APPIUM.IO     at ChildProcess.<anonymous> (/root/node_modules/teen_process/lib/exec.js:113:19)
2021-05-02T08:14:18.4688857Z ERR! APPIUM.IO     at ChildProcess.emit (node:events:365:28)
2021-05-02T08:14:18.4689492Z ERR! APPIUM.IO     at ChildProcess.emit (node:domain:470:12)
2021-05-02T08:14:18.4690384Z ERR! APPIUM.IO     at maybeClose (node:internal/child_process:1067:16)
2021-05-02T08:14:18.4691197Z ERR! APPIUM.IO     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
2021-05-02T08:14:18.4995850Z npm notice 
2021-05-02T08:14:18.4999587Z npm notice New minor version of npm available! 7.10.0 -> 7.11.2
2021-05-02T08:14:18.5000576Z npm notice Changelog: <https://github.com/npm/cli/releases/tag/v7.11.2>
2021-05-02T08:14:18.5001991Z npm notice Run `npm install -g npm@7.11.2` to update!
2021-05-02T08:14:18.5002987Z npm notice 
```

This error started happening in a few days since the previous `rc` release was succeeded...

**Comment by mykola-mokhnach** [comment]
this looks like mldocs issue. Shall we create an issue in https://github.com/mkdocs/mkdocs/ ?

**Comment by KazuCocoa** [comment]
Maybe gotcha. `0.17.5`+ works with Python3.7, but the current version should not.
Previous succeeded one was Python2 https://dev.azure.com/AppiumCI/Appium%20CI/_build/results?buildId=14993&view=logs&j=b9a26d17-edd7-534e-d332-dd86d02f1216&t=356869ca-715b-520e-c4c5-1c813195bf19

**Comment by KazuCocoa** [comment]
https://github.com/appium/appium.io/pull/304
